### PR TITLE
Rustup and update some dependencies

### LINKED ISSUE #16: Build broken with newer cargo nightly
```
$ rm rust-toolchain
$ cargo build
warning: unused manifest key: target.heroku.version
    Updating git repository `https://github.com/solson/miri.git`
    Updating git repository `https://github.com/oli-obk/Rocket.git`
error: no matching package named `miri` found
location searched: https://github.com/solson/miri.git?branch=rustup#7269a884
did you mean: mse
required by package `priroda v0.1.0 (/home/bjorn/Documenten/priroda)`
$ rm Cargo.lock
$ cargo build
warning: unused manifest key: target.heroku.version
    Updating git repository `https://github.com/oli-obk/cgraph.git`
    Updating crates.io index
    Updating git repository `https://github.com/solson/miri.git`
    Updating git repository `https://github.com/oli-obk/Rocket.git`
error: no matching package named `miri` found
location searched: https://github.com/solson/miri.git?branch=rustup
did you mean: mse
required by package `priroda v0.1.0 (/home/bjorn/Documenten/priroda)`
```

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes #16

### CODE REVIEW

**Comment by bjorn3** [comment]
When updating rocket I got:

```
error: unexpected keyed parameter: expected literal or identifier
   --> src/main.rs:167:11
    |
167 |       #[get(path = $route)]
    |             ^^^^^^^^^^^^^
    | 
   ::: src/render/mod.rs:260:5
    |
260 | /     view_route!(index: "/", |pcx, flash: FlashString| {
261 | |         render::render_main_window(pcx, None, flash.0)
262 | |     });
    | |_______- in this macro invocation
```

after I changed `#[get($route)]` to `#[get(path = $route)]` to make rocket happy.

File: src/watch/stack_trace.rs [hunk 1]
```diff
@@ -76,7 +76,7 @@ fn instance_for_call_operand<'a, 'tcx: 'a>(
             }
             ty::FnDef(def_id, substs) => {
                 let substs = ecx.tcx.subst_and_normalize_erasing_regions(
-                    ecx.substs(),
+                    ecx.stack().last().expect("top frame").instance.substs,
```
Comment (oli-obk) [inline src/watch/stack_trace.rs:79]: Won't this panic if we look at memory after the program finishes evaluation?

Comment (bjorn3) [reply src/watch/stack_trace.rs:79]: That won't happen, once the final return terminator is reached stepping will stop, so there is always at least one stack frame:

https://github.com/bjorn3/priroda/blob/0aec7250ab077a82d678ead19c367ab23092ff5b/src/step.rs#L95
